[package]
name = "lib_fl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fl-wasm-rs = "0.1.0"
serde_json = "1.0.85"
serde = { version = "1.0.145", features = ["derive"] }